import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header"; // Adjust path if needed
import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";
import { CartProvider } from "@/app/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className}antialiased`}
          suppressHydrationWarning
        >
          {/* <Header /> */}

          <Header />
          {children}

          <Footer />
        </body>
      </html>
    </CartProvider>
  );
}
