import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";
import { CartProvider } from "@/app/context/CartContext";
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider";
import ScrollToTop from "@/components/Header/Panel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

// Create a React Query client instance

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning
      >
        {/* Wrap the entire application with QueryClientProvider and CartProvider */}
        <ReactQueryClientProvider>
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </ReactQueryClientProvider>
        <ScrollToTop />
      </body>
    </html>
  );
}
